coordinate_system_name: "projector_coordinate_system"
coordinate_system_resolution: 574
coordinate_system_distance: 3000 

# Projector Reference System {P}
P1: {x:  10, y:  10}
P2: {x: 584, y:  10}
P3: {x: 584, y: 410}
P4: {x:  10, y: 410}

# User Reference System {T}
T1: {x: 10, y: 10}
  # T2, T3, T4 will be defined with the resolution