coordinate_system_name: "projector_coordinate_system"
coordinate_system_resolution: 574
coordinate_system_distance: 3000 

# Projector Reference System {P}
P0: {x:   0, y:   0}
P1: {x: 594, y:   0}
P2: {x: 594, y: 420}
P3: {x:   0, y: 420}

# User Reference System {T}
T0: {x: 0, y: 0}

# T2, T3, T4 will be autodefined with the resolution. See the docs
#      ____________________      
#   T4|                    |T3   ^
#     |                    |     | 
#     |                    |     | autoscale * resolution
#     |                    |     |
#   T1|____________________|T2   v
#      <--  autoscale * --> 
#           resolution

#  If {P} defines a square, autoscale = 1
#  If {P} defines a rectangle, autoscale = 1 only for largest dimension. 